columnSuffix: null
contentColumnType: string
fieldGroup: a6728ee5-3fbf-4246-9fc0-330a57e4f5ef # Common
handle: skipToQuestion
instructions: 'This is the question we should go to next if the user chooses to skip'
name: 'Skip to Question'
searchable: false
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: true
  source: null
  sources:
    - 'section:3e8e03c0-74ff-4354-8909-2b6bad8f24f5' # Quiz Steps
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
